name: Build jicmp for Kylin ARM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Install ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf autoconf automake libtool
        
    - name: Download and extract jicmp source
      run: |
        wget https://github.com/OpenNMS/jicmp/releases/download/jicmp-3.0.5-1/jicmp-3.0.5.tar.gz
        tar xzf jicmp-3.0.5.tar.gz
        
    - name: Configure and build
      run: |
        cd jicmp-3.0.5
        
        # 生成配置脚本
        autoreconf -fiv
        
        # 设置交叉编译环境
        export JAVA_HOME=$JAVA_HOME_8_X64
        export PATH=$JAVA_HOME/bin:$PATH
        
        # 配置编译选项
        ./configure \
          --host=arm-linux-gnueabihf \
          --prefix=/usr \
          --libdir=/usr/lib/arm-linux-gnueabihf
          
        # 编译
        make -j4
        
        # 准备构建产物
        mkdir -p output
        cp src/.libs/libjicmp.so output/
        cp jicmp.jar output/
        cp README output/
        
        # 创建版本信息
        echo "Build date: $(date)" > output/BUILD_INFO
        echo "GitHub Run ID: $GITHUB_RUN_ID" >> output/BUILD_INFO
        
    - name: Package artifacts
      run: |
        cd jicmp-3.0.5/output
        tar czf ../jicmp-kylin-arm.tar.gz *
        cd ..
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jicmp-kylin-arm
        path: jicmp-jicmp-3.0.5/jicmp-kylin-arm.tar.gz
        retention-days: 7
