name: Build fping for ARM64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git autoconf automake libtool \
            gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Clone fping
        run: |
          git clone https://github.com/schweikert/fping.git
          cd fping
          git checkout v5.1

      - name: Build for ARM64
        run: |
          cd fping
          ./autogen.sh
          ./configure \
            --host=aarch64-linux-gnu \
            CC=aarch64-linux-gnu-gcc
          make -j$(nproc)

      - name: Verify binary
        run: |
          file fping/fping | grep "ARM aarch64"
          chmod +x fping/fping

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fping-arm64
          path: fping/fping
          retention-days: 5
