name: Build for Kylin ARM64

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup ARM environment
        run: |
          dpkg --add-architecture arm64
          apt-get update
          apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libc6-dev:arm64 \
            automake autoconf libtool \
            openjdk-8-jdk-headless:arm64 \
            git make pkg-config

      - name: Configure for ARM64
        run: |
          export CC="aarch64-linux-gnu-gcc"
          export CXX="aarch64-linux-gnu-g++"
          export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
          
          autoreconf -fvi
          ./configure \
            --host=aarch64-linux-gnu \
            --build=x86_64-linux-gnu \
            --prefix=/usr

      - name: Build and package
        run: |
          make -j$(nproc)
          make DESTDIR=./arm64-build install

      - name: Collect artifacts
        run: |
          mkdir artifacts
          find . -name '*.so' -exec cp {} artifacts \;
          cp ./src/java/lib/jicmp6.jar artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jicmp6-arm64-binaries
          path: artifacts/*
