name: Build jicmp for Kylin ARM (OpenNMS branch)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Install ARM toolchain and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-linux-gnueabihf \
          g++-arm-linux-gnueabihf \
          autoconf \
          automake \
          libtool \
          pkg-config \
          unzip \
          libtool-bin
        
    - name: Download and extract jicmp source
      run: |
        wget https://github.com/OpenNMS/jicmp/archive/refs/heads/jira/JICMP-23.zip
        unzip JICMP-23.zip
        mv jicmp-jira-JICMP-23 jicmp-source
        
    - name: Patch build system
      run: |
        cd jicmp-source
        
        # 修复1: 添加缺失的 AM_RPM_INIT 宏定义
        cat >> aclocal.m4 << 'EOF'
        AC_DEFUN([AM_RPM_INIT], [
        dnl 空实现，跳过 RPM 初始化
        ])
        EOF
        
        # 修复2: 修改 configure.ac 跳过 RPM 检查
        sed -i '/AM_RPM_INIT/d' configure.ac
        
        # 修复3: 确保包含必要的宏
        echo "m4_include([aclocal.m4])" >> configure.ac
        
    - name: Configure and build
      run: |
        cd jicmp-source
        
        # 重新生成构建系统
        autoreconf -fiv
        
        # 设置Java环境
        export JAVA_HOME=$JAVA_HOME_8_X64
        export PATH=$JAVA_HOME/bin:$PATH
        
        # 配置ARM交叉编译
        ./configure \
          --host=arm-linux-gnueabihf \
          --prefix=/usr \
          --libdir=/usr/lib/arm-linux-gnueabihf \
          --with-jdk=$JAVA_HOME \
          --disable-rpm \  # 明确禁用 RPM
          --disable-static
        
        # 编译
        make -j4 V=1
        
        # 准备输出
        mkdir -p output
        cp src/.libs/libjicmp.so* output/ || find src -name "libjicmp.so*" -exec cp {} output/ \;
        cp jicmp.jar output/
        
        # 验证关键文件
        if [ ! -f "output/libjicmp.so" ]; then
          echo "错误：未找到 libjicmp.so!"
          find . -name "*.so*"  # 列出所有 .so 文件
          exit 1
        fi
        
        # 添加构建信息
        echo "Source: OpenNMS/jicmp branch jira/JICMP-23" > output/BUILD_INFO
        echo "Build date: $(date)" >> output/BUILD_INFO
        echo "GitHub Run ID: $GITHUB_RUN_ID" >> output/BUILD_INFO
        echo "Library path: $(find . -name libjicmp.so)" >> output/BUILD_INFO
        echo "Configure options: --host=arm-linux-gnueabihf --disable-rpm" >> output/BUILD_INFO
        
    - name: Package artifacts
      run: |
        cd jicmp-source/output
        tar czf ../jicmp-kylin-arm-opennms.tar.gz *
        cd ..
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jicmp-kylin-arm-opennms
        path: jicmp-source/jicmp-kylin-arm-opennms.tar.gz
        retention-days: 7
